# NumPy Assigmenmt (pratical questions)

Question 1)

Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [14]:
# we will import numpy
import numpy as np

# we will import random()
import random

arr= np.random.randint(1,101, size=(3,3))
arr


array([[79, 60, 13],
       [82, 39, 74],
       [53, 95, 33]])

In [15]:
arr1 = arr.T #it will interchange the or transpose the array
arr1

array([[79, 82, 53],
       [60, 39, 95],
       [13, 74, 33]])

Question 2)

 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.




In [18]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.reshape(arr,(2,5))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
np.reshape(arr,(5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Question 3)

Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [26]:

array_4x4 = np.random.random((4, 4))

array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", array_4x4)
print("\n6x6 Array with Zero Border:\n", array_6x6)

Original 4x4 Array:
 [[0.80409162 0.80122917 0.84642919 0.07980232]
 [0.10316009 0.49824668 0.70993225 0.07998376]
 [0.68480119 0.70818938 0.68637073 0.34550997]
 [0.59206626 0.24985747 0.37643301 0.51597769]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.80409162 0.80122917 0.84642919 0.07980232 0.        ]
 [0.         0.10316009 0.49824668 0.70993225 0.07998376 0.        ]
 [0.         0.68480119 0.70818938 0.68637073 0.34550997 0.        ]
 [0.         0.59206626 0.24985747 0.37643301 0.51597769 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Question 4)

Using NumPy, create an array of integers from 10 to 60 with a step of 5.




In [27]:
arr=np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Question 5)

 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [28]:
arr=np.array(['python','numpy','pandas'])
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [31]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [32]:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [33]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

Question 6)

Generate a NumPy array of words. Insert a space between each character of every word in the array.




In [34]:
words = np.array(["apple", "banana", "cherry", "date", "elderberry"])
words

array(['apple', 'banana', 'cherry', 'date', 'elderberry'], dtype='<U10')

In [40]:
np.char.join(" ", words)

array(['a p p l e', 'b a n a n a', 'c h e r r y', 'd a t e',
       'e l d e r b e r r y'], dtype='<U19')

Question 7) 

Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.




In [52]:
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(10,20,(2,2))
print(arr1)
print()
print(arr2)


[[8 1]
 [9 8]]

[[17 11]
 [16 12]]


In [51]:

arr1+arr2

array([[16, 19],
       [21, 24]])

In [48]:
arr1-arr2

array([[-10,  -1],
       [ -9, -12]])

In [49]:
arr1*arr2

array([[ 39,  90],
       [ 90, 108]])

In [50]:
arr1/arr2

array([[0.23076923, 0.9       ],
       [0.4       , 0.33333333]])

Question 8)

 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [53]:
matrix=np.eye(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.diagonal(matrix)

array([1., 1., 1., 1., 1.])

Question 9)

 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [64]:
arr=np.random.randint(0,1001,100)
arr

array([665, 946, 476, 233, 766, 846,  21, 482, 123, 128, 745, 224, 218,
       503, 421, 723, 426, 469, 122, 305, 824, 337,  54, 224, 393, 863,
       882, 135, 402, 963, 467, 751, 377, 136, 203, 133, 381, 171, 655,
       213, 306, 451, 105, 929, 579, 578, 307, 511, 777, 280, 999, 618,
       119, 707, 465, 242,  37, 717, 556,  99, 258,  57, 709,  49, 450,
       183, 928, 601, 248,  90, 255, 221, 324, 577, 439, 868, 464, 125,
       424, 414, 587, 510, 418, 245, 329, 252, 490, 887, 588, 947, 569,
       531, 570, 263, 571, 168, 601, 257, 751, 706])

In [66]:
is_prime = lambda num:num>1 and all(num%i!=0 for i in range(2,int(num**.5+1)))
prime_no= [num for num in arr if is_prime(num)]
print(prime_no)

[233, 503, 421, 337, 863, 467, 751, 929, 307, 37, 709, 601, 577, 439, 587, 887, 947, 569, 263, 571, 601, 257, 751]


Question 10) 

Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [85]:
temp=np.random.randint(25,30,30)
temp

array([25, 28, 27, 29, 25, 27, 27, 27, 25, 27, 26, 27, 28, 29, 27, 28, 28,
       28, 28, 25, 25, 26, 26, 27, 26, 27, 26, 27, 27, 29])

In [84]:
week1=temp[0:7]
print(week1)
print()
print("average is ",np.mean(week1))

[28 25 25 27 27 28 29]

average is  27.0


In [81]:
week2=temp[7:14]
print(week2)
print()
print("average is ",np.mean(week2))

[25 25 25 27 28 25 28]

average is  26.142857142857142


In [82]:
week3=temp[14:21]
print(week3)
print()
print("average is ",np.mean(week3))

[29 26 27 29 25 25 29]

average is  27.142857142857142


In [83]:
week4=temp[21:]
print(week4)
print()
print("average is ",np.mean(week4))

[26 28 25 28 28 28 28 25 26]

average is  26.88888888888889


# Theory Questions

Question 1)

 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Answer 1)

Purpose and Advantages of NumPy in Scientific Computing:
NumPy is a powerful Python library for numerical computing, enabling fast and efficient handling of large data sets. It enhances Python’s capabilities with its ndarray object, a high-performance multi-dimensional array, and provides a wide range of mathematical functions for operations like linear algebra, statistical computations, and Fourier transforms. The use of contiguous memory blocks improves performance and enables parallelization for faster computations.

Question 2)

 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Answer 2)

np.mean() vs np.average():

np.mean(): Computes the arithmetic mean of an array. It is simpler and used when no weights are needed.

np.average(): Computes a weighted mean if weights are specified. It offers more flexibility, especially when dealing with non-uniform distributions of data.

Use Case: Use np.mean() for simple averaging and np.average() when you need to apply weights to the data.

Question 3)

Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

Answer 3)

1D Array: You can reverse a 1D array using [::-1]

2D Array: Reverse along different axes using flipud() (up-down) and fliplr() (left-right).

We can also use np.roll() for reversing the array



In [91]:
arr = np.array([1, 2, 3])
reversed_arr = arr[::-1]  
reversed_arr


array([3, 2, 1])

In [89]:
arr = np.array([[1, 2], [3, 4]])
flip_ud = np.flipud(arr)   
flip_lr = np.fliplr(arr) 
flip_ud
flip_lr

array([[2, 1],
       [4, 3]])

Question 4)

How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Answer 4)

 check the data type using the .dtype
 
 Importance: Proper data types optimize memory usage and computation speed. For example, using float32 for large arrays can significantly save memory compared to using float64.


In [102]:
arr = np.array([1, 2, 3])
print(arr.dtype) 


int32


Question 5)

 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
 
Answer 5)

ndarray is the core data structure in NumPy. It is a multi-dimensional array that can store homogeneous data types efficiently.

Unlike Python lists, which are heterogeneous and can store mixed data types, ndarray offers better memory efficiency and faster operations.

Key Features: Fixed size, fast element-wise operations, and multi-dimensional support.

Question 6)

Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer 6)

NumPy arrays are much faster than Python lists for numerical computations. This is because NumPy arrays use contiguous memory and have optimized C-based operations, leading to reduced overhead. NumPy arrays support element-wise operations, making large-scale numerical operations more efficient.

Question 7)

Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Answer 7)



In [103]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.vstack((arr1, arr2))  
result


array([[1, 2],
       [3, 4]])

In [104]:
result = np.hstack((arr1, arr2))  
result


array([1, 2, 3, 4])

Question 8)

 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Answer 8)

In [108]:
arr = np.array([[1, 2], [3, 4]])
flipped = np.fliplr(arr)  
print(arr)
print()
print(flipped)

[[1 2]
 [3 4]]

[[2 1]
 [4 3]]


In [109]:
flipped = np.flipud(arr)  
print(arr)
print()
print(flipped)


[[1 2]
 [3 4]]

[[3 4]
 [1 2]]


Question 9)

Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer 9)

This method splits an array into multiple sub-arrays. If the array can't be split evenly, the extra elements are distributed across the splits.

In [110]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 4)  
result


[array([1, 2]), array([3, 4]), array([5]), array([6])]

Question 10)

 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Answer 10)

Vectorization: Refers to applying operations to entire arrays without the need for explicit loops. This speeds up computations by utilizing low-level optimizations.

Broadcasting: Allows NumPy to apply operations on arrays of different shapes, automatically expanding the smaller array to match the dimensions of the larger array. This enables efficient memory usage and operation.